### ISSUE TITLE
The /logout endpoint uses HTTP GET method, but this call changes the 'state' from the user perspective

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-jobs#129]
I'd suggest to use different method, because according to RFC2616:

'In particular, the convention has been established that the GET and HEAD methods SHOULD NOT have the significance of taking an action other than retrieval. These methods ought to be considered "safe". This allows user agents to represent other methods, such as POST, PUT and DELETE, in a special way, so that the user is made aware of the fact that a possibly unsafe action is being requested. '

**Comment by fridex** [comment]
The GET method was chosen so a user can directly log out by accessing /logout endpoint directly from browser, but I agree it's not that accurate based on RFC. As we are using Swagger UI, we can directly use PUT method.
