### ISSUE TITLE
Improve Jobs API concurrency

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-jobs#247]
We are currently encountering Gateway Timeouts when the Jobs API calls take very long time to process. This is already a known issue https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/164

Another issue that I realized is that the number of API workers are at present set to only 1. This causes other clients to wait until a request completes or fails. We can improve the concurrency of API workers to resolve this.

**Comment by fridex** [comment]
> Another issue that I realized is that the number of API workers are at present set to only 1. This causes other clients to wait until a request completes or fails. We can improve the concurrency of API workers to resolve this.

BTW see https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a-jobs.py#L109-L112

**Comment by tuxdna** [comment]
There are two options:

 * first is to increase the number of uwsgi workers here - https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/028e37e149d900dbade54d1529c89ad831b26a71/hack/run_jobs.sh#L7
 * second is to increase the number of replicas running inside OpenShift for Jobs Service - https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/openshift/template.yaml#L17

As @fridex mentioned above we also have to ensure that there is only one Jobs scheduler running in either case.

**Interesting mix of constraints here** :-)

**Comment by msrb** [comment]
This issue was moved to openshiftio/openshift.io#2220
