### ISSUE TITLE
Integration tests for jobs service broke CI/CD pipeline

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-jobs#82]
Integration tests for jobs service broke CI/CD pipeline as described in:

https://github.com/fabric8-analytics/fabric8-analytics-common/pull/79

It looks like Jenkins slaves are too slow to bring jobs service up before tests get executed. This is resulting in "Connection Refused" errors in tests. We should introduce a new feature - let's say "Then I wait for jobs service to start" that would wait for jobs service to get available for some time (and retry with a delay if cannot connect to the jobs service).

Integration tests are disabled for now due this issue.

**Comment by fridex** [comment]
Ping @tisnik, could you check this please once you will have time? Thanks!

**Comment by tisnik** [comment]
I'll look at it, thanks @fridex

**Comment by tisnik** [comment]
@fridex I'm just thinking aloud - we already have precondition "Given System is running", should not be the check for job service part of it. Or we could introduce something simila "Given Job service is running". What do you think?

**Comment by tisnik** [comment]
Actually the precondition "Given System is in initial state" checks core API, not "Given System is running"

**Comment by fridex** [comment]
> @fridex I'm just thinking aloud - we already have precondition "Given System is running", should not be the check for job service part of it. Or we could introduce something simila "Given Job service is running". What do you think?

Maybe also change "Given System is running" as it does not reflect semantics. Error messages and code structure in `environment.py` will need to be changed appropriately to report correct errors though.

BTW looking at the source code, there are still kubernetes leftovers. Maybe we could get rid of them as well as we will run only on OpenShift.

> Actually the precondition "Given System is in initial state" checks core API, not "Given System is running"

Yeah, an archaic leftover. Jobs service was introduced later, there was only API server for system interaction.

Thanks for working on this!

**Comment by jpopelka** [comment]
> BTW looking at the source code, there are still kubernetes leftovers. Maybe we could get rid of them as well as we will run only on OpenShift.

+1

I was going to remove them in the unfinished https://github.com/fabric8-analytics/fabric8-analytics-common/pull/10 too

**Comment by fridex** [comment]
Related to this issue: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/85

**Comment by fridex** [comment]
This issue was resolved, closing...
