### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by pombredanne** [fabric8-analytics/fabric8-analytics-jobs#86]
Any specific reason why this repo is GPL-licensed when most of the other fabric8-analytics and fabric8io repos are Apache-licensed (except may be for https://github.com/fabric8-analytics/fabric8-analytics-recommender and https://github.com/fabric8-analytics/fabric8-analytics-data-model which are also GPL )? Just curious!

**Comment by msrb** [comment]
Hi Philippe,

Thanks for hanging out with us. The license is ASL 2.0 - we now have license file in this repo and GitHub is also reporting correct license.

**Comment by pombredanne** [comment]
@msrb Thanks Michal!
So I reckon that the other repos such as these stay GPL, correct?
- https://github.com/fabric8-analytics/fabric8-analytics-recommender/blob/master/LICENSE
- https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/LICENSE
- https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/LICENSE
